name       : libgdiplus
version    : 6.0.5
release    : 8
source     :
    - https://github.com/mono/libgdiplus/archive/6.0.5.tar.gz : 1fd034f4b636214cc24e94c563cd10b3f3444d9f0660927b60e63fd4131d97fa
license    : MIT
component  : desktop.library
summary    : An Open Source implementation of the GDI+ API
description: |
    An Open Source implementation of the GDI+ API.
libsplit   : no
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libexif)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - dejavu-fonts-ttf # Tests
    - giflib-devel
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
