name       : libgdiplus
version    : 5.6
release    : 5
source     :
    - https://github.com/mono/libgdiplus/archive/5.6.tar.gz : 6a75e4a476695cd6a1475fd6b989423ecf73978fd757673669771d8a6e13f756
license    : MPL-1.1
component  : desktop.library
summary    : An Open Source implementation of the GDI+ API
description: |
    An Open Source implementation of the GDI+ API.
libsplit   : no
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libexif)
    - pkgconfig(libturbojpeg)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
