name       : libgdiplus
version    : 3.12
release    : 3
source     :
    - https://github.com/mono/libgdiplus/archive/3.12.tar.gz : 7eadc5105c6352d456c5f8699dc89260bf402e82ce6668e7e0c625519f9e5b44
license    : MPL-1.1
summary    : An Open Source implementation of the GDI+ API.
description: |
    An Open Source implementation of the GDI+ API.
libsplit : no
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libexif)
setup      : |
    autoreconf -vfi
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
