name       : libgdiplus
version    : 6.0.4
release    : 7
source     :
    - https://github.com/mono/libgdiplus/archive/6.0.4.tar.gz : 9a5e3f98018116f99361520348e9713cd05680c231d689a83d87acfaf237d3a8
license    : MIT
component  : desktop.library
summary    : An Open Source implementation of the GDI+ API
description: |
    An Open Source implementation of the GDI+ API.
libsplit   : no
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(libexif)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - dejavu-fonts-ttf # Tests
    - giflib-devel
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
