name       : libgdiplus
version    : 3.12
release    : 1
source     :
    - https://github.com/mono/libgdiplus/archive/3.12.tar.gz : 7eadc5105c6352d456c5f8699dc89260bf402e82ce6668e7e0c625519f9e5b44
license    : MPL-1.1
summary    : An Open Source implementation of the GDI+ API.
description: |
    An Open Source implementation of the GDI+ API.
builddeps  :
    - libcairo
    - libcairo-devel
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(libexif)
setup      : |
    libtoolize --force
    aclocal
    autoheader
    automake --force-missing --add-missing
    autoconf
    chmod +x configure
    %configure
build      : |
    %make
install    : |
    %make_install
